import { useState } from "react";

import { Chip, CopyButton, Countdown, Modal, StatusChip } from "./components";
import { formatDateTime } from "./format";
import type { GeneratedKey, KeyView } from "./types";

/**
 * Security keys as every screen may show them: masked, with lifecycle state — never the key itself
 * (BRD v1.3, CP-SEC-08). While a rotation is open, the previous key shows its countdown to expiry.
 */
export function KeyTable({ keys, onRevoke, revoking }: {
  keys: KeyView[];
  /** Admin only: revoke a newly generated key inside the overlap window (CP-SEC-06). */
  onRevoke?: (key: KeyView) => void;
  revoking?: string | null;
}) {
  if (keys.length === 0) {
    return <div className="empty">No keys have been issued yet.</div>;
  }
  const rotationOpen = new Set(keys.filter((k) => k.status === "EXPIRING").map((k) => k.environment));
  return (
    <table className="table">
      <thead>
        <tr>
          <th>Key</th>
          <th>Environment</th>
          <th>Status</th>
          <th>Generated</th>
          <th>Generated by</th>
          <th>Expires in</th>
          {onRevoke ? <th /> : null}
        </tr>
      </thead>
      <tbody>
        {keys.map((k) => (
          <tr key={k.id}>
            <td className="mono" style={{ fontSize: 12 }}>{k.maskedKey}</td>
            <td><Chip tone={k.environment === "PRODUCTION" ? "ok" : "info"}>{k.environment}</Chip></td>
            <td><StatusChip status={k.status} /></td>
            <td className="mono muted" style={{ fontSize: 11.5 }}>{formatDateTime(k.createdAt)}</td>
            <td style={{ fontSize: 12 }}>{k.createdBy}</td>
            <td style={{ fontSize: 12 }}>
              {k.status === "EXPIRING" ? <Countdown until={k.expiresAt} />
                : k.endedAt ? <span className="muted">ended {formatDateTime(k.endedAt)}</span> : "—"}
            </td>
            {onRevoke ? (
              <td style={{ textAlign: "right" }}>
                {k.status === "ACTIVE" && rotationOpen.has(k.environment) ? (
                  <button className="btn btn-sm btn-danger" disabled={revoking === k.id} onClick={() => onRevoke(k)}>
                    Revoke new key
                  </button>
                ) : null}
              </td>
            ) : null}
          </tr>
        ))}
      </tbody>
    </table>
  );
}

/** The only moment a key is ever visible. Closing requires confirming it has been stored. */
export function GeneratedKeyModal({ generated, onClose }: { generated: GeneratedKey; onClose: () => void }) {
  const [stored, setStored] = useState(false);
  return (
    <Modal
      title={`New ${generated.key.environment.toLowerCase()} key`}
      onClose={() => stored && onClose()}
      footer={
        <>
          <label className="row grow" style={{ gap: 8, fontSize: 12.5 }}>
            <input type="checkbox" checked={stored} onChange={(e) => setStored(e.target.checked)} />
            I have stored this key in our secret manager
          </label>
          <button className="btn btn-primary" disabled={!stored} onClick={onClose}>Done</button>
        </>
      }
    >
      <p className="muted" style={{ fontSize: 12.5, lineHeight: 1.6 }}>
        Copy it now. This is the only time the full key is shown — afterwards you will see only the masked form, and
        nobody, including administrators, can retrieve it.
      </p>
      <div className="secret">{generated.plaintext}</div>
      <div className="row">
        <CopyButton value={generated.plaintext} label="Copy key" />
        <span className="muted" style={{ fontSize: 12 }}>
          Client ID <span className="mono">{generated.clientId}</span>
        </span>
      </div>
      {generated.previousKeyExpiresAt ? (
        <div className="banner banner-warn">
          <span>
            Your previous key keeps working for <strong><Countdown until={generated.previousKeyExpiresAt} /></strong>
            {" "}(until {formatDateTime(generated.previousKeyExpiresAt)}). Switch every system to the new key before then.
          </span>
        </div>
      ) : null}
    </Modal>
  );
}
