-- Baseline schema for the API Gateway control plane.
-- Written to run on PostgreSQL and on H2 in PostgreSQL mode (tests and the no-Docker profile).

CREATE TABLE partner_group (
    id          UUID          PRIMARY KEY,
    name        VARCHAR(120)  NOT NULL UNIQUE,
    description VARCHAR(500),
    status      VARCHAR(20)   NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE partner (
    id                   UUID          PRIMARY KEY,
    code                 VARCHAR(20)   NOT NULL UNIQUE,
    name                 VARCHAR(160)  NOT NULL,
    group_id             UUID          NOT NULL REFERENCES partner_group (id),
    access_tier          VARCHAR(20)   NOT NULL,
    status               VARCHAR(20)   NOT NULL,
    contact_email        VARCHAR(200),
    -- BRD v1.3: a Client ID is issued per partner per environment; rate limits are counted against it.
    client_id_sandbox    VARCHAR(64)   NOT NULL UNIQUE,
    client_id_production VARCHAR(64)   UNIQUE,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE api_definition (
    id                     UUID          PRIMARY KEY,
    name                   VARCHAR(160)  NOT NULL,
    category               VARCHAR(60)   NOT NULL,
    http_method            VARCHAR(10)   NOT NULL,
    proxy_path             VARCHAR(200)  NOT NULL,
    backend_url_sandbox    VARCHAR(300)  NOT NULL,
    backend_url_production VARCHAR(300),
    status                 VARCHAR(20)   NOT NULL,
    guest_visible          BOOLEAN       NOT NULL,
    rate_limit_count       INTEGER       NOT NULL,
    rate_limit_window      VARCHAR(10)   NOT NULL,
    owner_team             VARCHAR(120),
    description            VARCHAR(2000),
    disabled_at            TIMESTAMP WITH TIME ZONE,
    created_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_api_route UNIQUE (http_method, proxy_path)
);

CREATE TABLE security_key (
    id          UUID          PRIMARY KEY,
    partner_id  UUID          NOT NULL REFERENCES partner (id),
    environment VARCHAR(20)   NOT NULL,
    -- BRD v1.3, CP-SEC-09: only a SHA-256 hash of the key is stored; the key itself is never persisted.
    key_hash    VARCHAR(64)   NOT NULL UNIQUE,
    masked_key  VARCHAR(40)   NOT NULL,
    status      VARCHAR(20)   NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by  VARCHAR(120)  NOT NULL,
    expires_at  TIMESTAMP WITH TIME ZONE,
    ended_at    TIMESTAMP WITH TIME ZONE
);
CREATE INDEX ix_security_key_partner_env ON security_key (partner_id, environment, status);
CREATE INDEX ix_security_key_expiry ON security_key (status, expires_at);

CREATE TABLE usage_event (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    api_id      UUID,
    environment VARCHAR(20),
    client_id   VARCHAR(64),
    status_code INTEGER       NOT NULL,
    latency_ms  INTEGER       NOT NULL
);
CREATE INDEX ix_usage_event_time ON usage_event (occurred_at);

CREATE TABLE audit_event (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    actor       VARCHAR(120)  NOT NULL,
    actor_role  VARCHAR(30),
    action      VARCHAR(40)   NOT NULL,
    object_type VARCHAR(40)   NOT NULL,
    object_id   VARCHAR(80),
    detail      VARCHAR(1000)
);
CREATE INDEX ix_audit_event_time ON audit_event (occurred_at);
