-- Operational errors, kept in the database so an operator can see what failed without shell access to logs:
-- rejected e-mails, gateway calls that did not answer, scheduled jobs that threw, and any unhandled
-- exception from an HTTP request.
--
-- Deliberately separate from audit_event: that records what people did, this records what went wrong.
-- Append-only, no foreign keys (a failure must survive whatever it refers to), purged by ErrorRetentionJob.

CREATE TABLE error_event (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    source       VARCHAR(40)   NOT NULL,   -- SMTP | GATEWAY | SCHEDULER | API | STARTUP
    code         VARCHAR(60)   NOT NULL,   -- INTERNAL_ERROR, SMTP_REJECTED, ...
    message      VARCHAR(1000) NOT NULL,   -- the server's own words, never a secret
    detail       VARCHAR(8000),            -- trimmed stack trace
    actor        VARCHAR(120),             -- who was signed in, when there was a request
    request      VARCHAR(300),             -- method and path
    client_ip    VARCHAR(60),
    reference    VARCHAR(40)   NOT NULL    -- short id shown to the caller, to match a report to a row
);

CREATE INDEX idx_error_event_occurred ON error_event (occurred_at DESC);
CREATE INDEX idx_error_event_source ON error_event (source, occurred_at DESC);
